openapi: 3.0.3
info:
  description: example
  title: test
  version: 0.0.0
servers:
- url: /
paths:
  /test:
    post:
      operationId: test
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Participant'
          description: Ok
      summary: Test
components:
  schemas:
    Participant:
      example:
        data:
          relationships:
            user:
              links: https://api.example.com/v1/users/1
          attributes:
            role: role
            updated_at: 2021-01-01T00:00:00Z
            verified: verified
            second_name: second_name
            created_at: 2021-01-01T00:00:00Z
            third_name: third_name
            position: position
            display_name: display_name
            first_name: first_name
            desc: desc
          id: id
          type: participant
      properties:
        data:
          $ref: '#/components/schemas/Participant_data'
      required:
      - data
      type: object
    ParticipantCreate:
      properties:
        data:
          $ref: '#/components/schemas/ParticipantCreate_data'
      required:
      - data
      type: object
    ParticipantUpdate:
      properties:
        data:
          $ref: '#/components/schemas/ParticipantUpdate_data'
      required:
      - data
      type: object
    ParticipantsCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/Participant'
          type: array
        links:
          $ref: '#/components/schemas/ParticipantsCollection_links'
        meta:
          $ref: '#/components/schemas/ParticipantsCollection_meta'
      required:
      - data
      - links
      - meta
      type: object
    OrganizationCreate:
      properties:
        data:
          $ref: '#/components/schemas/OrganizationCreate_data'
      required:
      - data
      type: object
    OrganizationUpdate:
      properties:
        data:
          $ref: '#/components/schemas/OrganizationUpdate_data'
      required:
      - data
      type: object
    OrganizationLinksUpdate:
      properties:
        data:
          $ref: '#/components/schemas/OrganizationLinksUpdate_data'
      required:
      - data
      type: object
    Links:
      properties:
        twitter:
          description: Twitter profile link
          format: uri
          type: string
        instagram:
          description: Instagram profile link
          format: uri
          type: string
        facebook:
          description: Facebook profile link
          format: uri
          type: string
        tiktok:
          description: TikTok profile link
          format: uri
          type: string
        linkedin:
          description: LinkedIn profile link
          format: uri
          type: string
        telegram:
          description: Telegram profile link
          format: uri
          type: string
        discord:
          description: Discord profile link
          format: uri
          type: string
        website:
          description: Companies website
          format: uri
          type: string
      type: object
    ComplicatedStatus:
      properties:
        state:
          description: Current compliance state of the organization
          enum:
          - active
          - suspended
          - inactive
          type: string
        stamp:
          format: string
          items:
            description: TODO default missing array inner type to string
            type: string
          type: array
        from:
          description: Date from which the compliance state is effective
          format: date-time
          type: string
      required:
      - from
      - stamp
      - state
      type: object
    Organization:
      properties:
        data:
          $ref: '#/components/schemas/Organization_data'
        included:
          items:
            $ref: '#/components/schemas/Participant'
          type: array
      required:
      - data
      type: object
    ParticipantCollection:
      properties:
        data:
          items:
            $ref: '#/components/schemas/Participant'
          type: array
        links:
          $ref: '#/components/schemas/ParticipantsCollection_links'
        meta:
          $ref: '#/components/schemas/ParticipantsCollection_meta'
      required:
      - data
      - links
      - meta
      type: object
    Participant_data_attributes:
      example:
        role: role
        updated_at: 2021-01-01T00:00:00Z
        verified: verified
        second_name: second_name
        created_at: 2021-01-01T00:00:00Z
        third_name: third_name
        position: position
        display_name: display_name
        first_name: first_name
        desc: desc
      properties:
        first_name:
          description: first name of participant
          type: string
        second_name:
          description: second name of participant
          type: string
        third_name:
          description: third name of participant
          type: string
        display_name:
          description: name of participant
          type: string
        position:
          description: position in the company
          type: string
        verified:
          description: verified status
          type: string
        desc:
          description: description of participant
          type: string
        role:
          description: User role
          type: string
        updated_at:
          description: User updated at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
        created_at:
          description: User created at
          example: 2021-01-01T00:00:00Z
          format: date-time
          type: string
      required:
      - created_at
      - desc
      - display_name
      - first_name
      - position
      - role
      - second_name
      - verified
      type: object
    Participant_data_relationships_user:
      example:
        links: https://api.example.com/v1/users/1
      properties:
        links:
          description: Link to user
          example: https://api.example.com/v1/users/1
          type: string
      required:
      - links
      type: object
    Participant_data_relationships:
      example:
        user:
          links: https://api.example.com/v1/users/1
      properties:
        user:
          $ref: '#/components/schemas/Participant_data_relationships_user'
      required:
      - user
      type: object
    Participant_data:
      example:
        relationships:
          user:
            links: https://api.example.com/v1/users/1
        attributes:
          role: role
          updated_at: 2021-01-01T00:00:00Z
          verified: verified
          second_name: second_name
          created_at: 2021-01-01T00:00:00Z
          third_name: third_name
          position: position
          display_name: display_name
          first_name: first_name
          desc: desc
        id: id
        type: participant
      properties:
        id:
          description: user id
          type: string
        type:
          enum:
          - participant
          type: string
        attributes:
          $ref: '#/components/schemas/Participant_data_attributes'
        relationships:
          $ref: '#/components/schemas/Participant_data_relationships'
      required:
      - attributes
      - id
      - type
      type: object
    ParticipantCreate_data_attributes:
      properties:
        org_id:
          description: organization ID
          type: string
        user_id:
          description: user ID
          type: string
        first_name:
          description: first name of participant
          type: string
        second_name:
          description: second name of participant
          type: string
        third_name:
          description: third name of participant
          type: string
        display_name:
          description: name of participant
          type: string
        position:
          description: position in the company
          type: string
        desc:
          description: description of participant
          type: string
        role:
          description: participant role
          type: string
      required:
      - desc
      - display_name
      - first_name
      - org_id
      - position
      - role
      - second_name
      - user_id
      type: object
    ParticipantCreate_data:
      properties:
        type:
          enum:
          - participant_create
          type: string
        attributes:
          $ref: '#/components/schemas/ParticipantCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    ParticipantUpdate_data_attributes:
      properties:
        org_id:
          description: Organization id
          type: string
        first_name:
          description: first name of participant
          type: string
        second_name:
          description: second name of participant
          type: string
        third_name:
          description: third name of participant
          type: string
        display_name:
          description: name of participant
          type: string
        position:
          description: position in the company
          type: string
        desc:
          description: Description
          type: string
        role:
          description: User role
          type: string
      required:
      - org_id
      type: object
    ParticipantUpdate_data:
      properties:
        id:
          description: user Id
          type: string
        type:
          enum:
          - participant_update
          type: string
        attributes:
          $ref: '#/components/schemas/ParticipantUpdate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    ParticipantsCollection_links:
      properties:
        self:
          description: Link to the current page
          type: string
        next:
          description: Link to the next page
          type: string
      type: object
    ParticipantsCollection_meta:
      properties:
        total:
          description: Total number of participant
          type: integer
      type: object
    OrganizationCreate_data_attributes_owner:
      properties:
        first_name:
          description: first name of participant
          type: string
        second_name:
          description: second name of participant
          type: string
        third_name:
          description: third name of participant
          type: string
        display_name:
          description: name of participant
          type: string
        position:
          description: position in the company
          type: string
        desc:
          description: description of participant
          type: string
      required:
      - desc
      - display_name
      - first_name
      - position
      - second_name
      type: object
    OrganizationCreate_data_attributes:
      properties:
        name:
          description: Team name
          type: string
        desc:
          description: Team description
          type: string
        sort:
          description: Type of Organization
          type: string
        country:
          description: Country of registration
          type: string
        owner:
          $ref: '#/components/schemas/OrganizationCreate_data_attributes_owner'
        city:
          description: City of HQ
          type: string
      required:
      - country
      - desc
      - name
      - owner
      - sort
      type: object
    OrganizationCreate_data:
      properties:
        type:
          enum:
          - organization_create
          type: string
        attributes:
          $ref: '#/components/schemas/OrganizationCreate_data_attributes'
      required:
      - attributes
      - type
      type: object
    OrganizationUpdate_data_attributes:
      properties:
        name:
          description: Team name
          type: string
        desc:
          description: Team description
          type: string
        sort:
          description: Type of Organization
          type: string
        country:
          description: Country of registration
          type: string
        city:
          description: City of HQ
          type: string
      type: object
    OrganizationUpdate_data:
      properties:
        id:
          description: organization id
          type: string
        type:
          enum:
          - organization_update
          type: string
        attributes:
          $ref: '#/components/schemas/OrganizationUpdate_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    OrganizationLinksUpdate_data:
      properties:
        id:
          description: Organization ID
          type: string
        type:
          enum:
          - organization_link_update
          type: string
        attributes:
          $ref: '#/components/schemas/Links'
      required:
      - attributes
      - id
      - type
      type: object
    Organization_data_attributes:
      properties:
        name:
          description: Team name
          type: string
        logo:
          description: Link to photo
          type: string
        verified:
          description: Verified status
          type: string
        desc:
          description: Team description
          type: string
        sort:
          description: Type of Organization
          type: string
        country:
          description: Country of registration
          type: string
        city:
          description: City of HQ
          type: string
        links:
          $ref: '#/components/schemas/Links'
        complicated_status:
          $ref: '#/components/schemas/ComplicatedStatus'
        created_at:
          description: Team creation timestamp
          format: date-time
          type: string
      required:
      - country
      - created_at
      - desc
      - logo
      - name
      - sort
      - verified
      type: object
    Organization_data:
      properties:
        id:
          description: organization id
          type: string
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: '#/components/schemas/Organization_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
